spring:
  profiles:
    include: dev

mybatis:
    typeAliasesPackage: com.**.mapper
    #mapperLocations: classpath:com/**/mapper/*.xml
    mapperLocations: /resources/com/**/mapper/*.xml

logging:
  file: ../log/springboot.log
