jasypt:
  encryptor:
    password: 123456
spring:
  datasource:
    #url: jdbc:mysql://172.16.100.130:3306/springboot?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: docma
    password: docma
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource



